### PR TITLE
Handle duplicate snapshot name error

### PR DESCRIPTION
**Pull request by mfazekas**
Fixes: #16

### CODE REVIEW

**Comment by timhaines** [comment]
I'm 99% sure our common practice is not to error on duplicate snapshot names, but to silently ignore one.  This is because in several parallel test environments a single snapshot may be run more than once, so we want to tolerate it.  Is this correct @fotinakis ?

**Comment by mfazekas** [comment]
@timhaines percy.io service itself returns an error for duplicate names `400/bad_request/ The name of each snapshot must be unique` but this case tests for a different snapshots sha-s with the same name.

**Comment by timhaines** [comment]
@mfazekas It does, yep.  The Ruby client [raises this as a BadRequestError](https://github.com/percy/percy-client/blob/cfe1131667925efb90282eff42b92dd20115db79/lib/percy/client/connection.rb#L25) which is then [caught and logged in percy-capybara, but not re-raised](https://github.com/percy/percy-capybara/blob/7f831a065fb26c2eefdbaa708e780a795bc4f717/lib/percy/capybara/client/snapshots.rb#L41).

I suspect percy-js and percy-ember do the same thing.  Will take a quick look and re-comment if they don't.

**Comment by timhaines** [comment]
@mfazekas And sorry - I missed your explanation here of "but this case tests for a different snapshots sha-s with the same name.".   Will take another look in the morning. :)

**Comment by mfazekas** [comment]
Thanks @timhaines  good catch. Make sense i guess we don't want to fail the user's tests just because percy calls are failing. percy-js is too low level to do this. 
I'll rework this PR.

**Comment by timhaines** [comment]
Thanks @mfazekas!  I've confirmed the tests passed locally, thanks to Travis having problems today.  Shipping this as 0.1.5.

**Pull request merged**
